// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdbbicqueswqjdchqxme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYmJpY3F1ZXN3cWpkY2hxeG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzY5ODUsImV4cCI6MjA2MDM1Mjk4NX0.2YRI3BROG5z2j1Gr9NZBqO2XdVD3kYQxV496TAJjkwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);